apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: client
spec:
  spiffeIDTemplate: "spiffe://example.org/ns/spire-playground/sa/client"

  workloadSelectorTemplates:
    - "k8s:ns:spire-playground"
    - "k8s:sa:client"