apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: spire-playground
spec:
  serviceAccountName: nginx

  volumes:
    - name: spiffe-workload-api
      csi:
        driver: csi.spiffe.io
        readOnly: true

  containers:
    - name: nginx
      image: nginx:stable

      volumeMounts:
        - name: spiffe-workload-api
          mountPath: /spiffe-workload-api
          readOnly: true